theme: jekyll-theme-divd

paginate: 10
plugins: [jekyll-paginate]
paginate_path: "blog/:num/"

language: nl-nl

title: Jekyll Theme DIVD
description: "Making the internet safer through Coordinated Vulnerability Disclosure"
repository: DIVD-NL/jekyll-theme-divd

timezone: Europe/Amsterdam
future: true
encoding: utf-8

permalink: pretty
markdown: kramdown
show_downloads: false
github:
  is_project_page: false

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-paginate
#  - jekyll-secinfo

#jekyll-secinfo:
#  divd:
#    url: /cases/DIVD-

# Theme settings
divd:
  skip-to-content-link: true
  colors:
    theme-color: '#157878'

# Custom headers
webrick:
  headers:
    Content-Security-Policy: default-src 'none'; font-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'; connect-src 'self'; frame-src none;

# Collections
collections:

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"    


exclude:
  - serve
  - "*.sh"
  - .keep
  - Gemfile
  - Gemfile.lock
  - "*.conf"
  - "*:Zone.Identifier"
