#theme: jekyll-theme-cayman

#paginate: 10
#plugins: [jekyll-paginate]
#paginate_path: "blog/:num/"

language: nl-nl

title: DIVD.fund
description: "Making the internet safer through Coordinated Vulnerability Disclosure"
repository: DIVD-NL/divd.fund

timezone: Europe/Amsterdam
future: true
encoding: utf-8


permalink: pretty
markdown: kramdown
show_downloads: false
github:
  is_project_page: false

#plugins:
#  - jekyll-sitemap
#  - jekyll-redirect-from
#  - jekyll-secinfo
#  - jekyll-paginate
#  - jekyll-last-modified-at

#jekyll-secinfo:
#  divd:
#    url: /cases/DIVD-

# Custom headers
webrick:
  headers:
    Content-Security-Policy: default-src 'none'; font-src 'self'; img-src 'self' data:; script-src 'self' https://assets.calendly.com; style-src 'self'; connect-src 'self'; frame-src https://calendly.com;

# Collections
collections:

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"    


exclude:
  - README.md
  - serve*
  - "*.sh"
  - .keep
  - Gemfile
  - Gemfile.lock
  - "*.conf"
  - "*:Zone.Identifier"
